name: Build Logging

on:
  workflow_dispatch:
  push:
    branches: [ logging ]
  pull_request:
    branches: [ logging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Release Source/Meadow.Foundation.Libraries_and_Frameworks/Meadow.Logging/lib/Meadow.Logging.csproj
