name: NuGet Package Creation

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build -c Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack -c Release lib/Meadow.Logging.csproj /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Meadow.Logging.${VERSION}.nupkg --source https://nuget.pkg.github.com/Meadow/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
